# Generated by Django 2.0.3 on 2019-06-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='numToppings',
            field=models.CharField(choices=[('0', 'Cheese'), ('1', '1 Topping'), ('2', '2 Toppings'), ('3', '3 Toppings'), ('X', 'Special')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='dinnerplatter',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='type',
            field=models.CharField(choices=[('SIC', 'Sicilian'), ('REG', 'Regular')], max_length=3),
        ),
        migrations.AlterField(
            model_name='sub',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1),
        ),
    ]
