# Generated by Django 2.0.3 on 2019-07-03 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190627_1808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salads',
            new_name='Salad',
        ),
    ]
