# Generated by Django 2.0.3 on 2019-07-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190705_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.CharField(default='None', max_length=64),
        ),
    ]
