# Generated by Django 2.0.3 on 2019-07-19 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190719_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='foods',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='toppings',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
