# Generated by Django 2.0.3 on 2019-07-23 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='foods',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='toppings',
        ),
        migrations.AddField(
            model_name='order',
            name='orderdetails',
            field=models.ManyToManyField(through='orders.OrderDetail', to='orders.Food'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Food', to='orders.Food'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='quanity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
