# Generated by Django 2.0.3 on 2019-07-23 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20190723_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='food',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Food', to='orders.Food'),
        ),
    ]
