# Generated by Django 2.0.3 on 2019-07-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20190723_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='topping',
            field=models.ManyToManyField(to='orders.Topping'),
        ),
    ]
