# Generated by Django 2.0.3 on 2019-07-23 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20190723_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
